// Shared regular expressions and constants used by the PR governance scripts.
// Keeping these in one place avoids the branch-name, title and commit checks
// silently drifting apart.
'use strict';

// Conventional Commits types allowed across branch names, PR titles and
// commit messages.
const COMMIT_TYPES = [
  'feat',
  'fix',
  'refactor',
  'perf',
  'test',
  'docs',
  'build',
  'ci',
  'chore',
  'revert',
  'style',
];

const TYPES_PATTERN = COMMIT_TYPES.join('|');

// Branch names: "<type>/<short-description>", lowercase, dots/underscores/
// dashes allowed in the description.
const BRANCH_NAME_RE = new RegExp(`^(${TYPES_PATTERN})/[a-z0-9._-]+$`);

// Conventional Commits header, optionally scoped and/or breaking ("!").
const CONVENTIONAL_COMMIT_RE = new RegExp(
  `^(${TYPES_PATTERN})(\\([a-z0-9._-]+\\))?!?: .+`
);

// Any character outside printable ASCII (covers emojis and other
// decorative/non-ASCII symbols).
const NON_ASCII_RE = /[^\x00-\x7F]/;

// AI attribution patterns to reject from commit messages and PR bodies.
// Matches known AI tool names/services and common "generated by" phrasing.
const AI_TOOL_NAMES =
  'claude|anthropic|copilot|openai|chatgpt|gpt|gemini|cursor|codeium|tabnine|devin|aider';
const AI_ATTRIBUTION_PATTERNS = [
  new RegExp(`co-authored-by:.*(${AI_TOOL_NAMES})`, 'i'),
  /noreply@anthropic\.com/i,
  /generated with/i,
  new RegExp(`generated by\\s*\\(?(ai|${AI_TOOL_NAMES})`, 'i'),
  /\u{1F916}/u, // robot emoji
];

// Bot accounts that should never be assigned or otherwise treated as a
// human PR author.
const BOT_LOGINS = ['dependabot[bot]'];

module.exports = {
  COMMIT_TYPES,
  BRANCH_NAME_RE,
  CONVENTIONAL_COMMIT_RE,
  NON_ASCII_RE,
  AI_ATTRIBUTION_PATTERNS,
  BOT_LOGINS,
};
